export declare const toLowerCase: (str: string) => string;
export declare const replaceTypeName: (type: any, replace: any) => any;
export declare const toDashCase: (str: string) => string;
export declare function camelCase(str: string, firstCapital?: boolean): string;
export declare function snakeCase(str: string): string;
export declare function checkString(str: string, _?: string): string;
export declare function titleCase(str: string): string;
export declare function abbreviate(str: string, abbrLettersCount?: number): string;
export declare const dashToPascalCase: (str: string) => string;
export declare const toTitleCase: typeof titleCase;
export declare const captializeFirstLetter: (str: string) => string;
export declare const toLTitleCase: (str: string) => string;
