"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("./scss"), exports);
tslib_1.__exportStar(require("./ts"), exports);
tslib_1.__exportStar(require("./image"), exports);
tslib_1.__exportStar(require("./copy"), exports);
tslib_1.__exportStar(require("./clean"), exports);
tslib_1.__exportStar(require("./_gulp"), exports);
tslib_1.__exportStar(require("./packages"), exports);
tslib_1.__exportStar(require("./uglify"), exports);
tslib_1.__exportStar(require("./list"), exports);
tslib_1.__exportStar(require("./wxapp"), exports);
