"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
var decorator_1 = require("./decorator");
exports.Client = decorator_1.GrpcClient;
exports.Server = decorator_1.GrpcServer;
exports.Router = decorator_1.GrpcRouter;
tslib_1.__exportStar(require("./grpc.visitor"), exports);
const grpc_visitor_1 = require("./grpc.visitor");
const ims_decorator_1 = require("ims-decorator");
exports.injector = ims_decorator_1.injector(new grpc_visitor_1.GrpcVisitor());
