version: '2'
services:
  node:
    image: 'node'
    volumes:
      - ./:/imeepos
      - ./src/:/imeepos/src/
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    command: 'npm run nodemon'
    restart: always
    working_dir: /imeepos
  db:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USERNAME: root
      MYSQL_DATABASE: meepo
      MYSQL_ROOT_PASSWORD: yang1989.
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
  memcached:
    image: 'memcached'
    ports:
      - '11211:11211'
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
