export declare const ROOT: string;
export declare const DATA_PATH: string;
export declare const CORE_DB_PATH: string;
export declare const INSTALL_LOCK: string;
export declare const DEFAULT_PRIVATE_KEY: string;
export declare const PUBLIC_PATH: string;
export declare const WEB_TEMPLATE_PATH: string;
export declare const WEB_TEMPLATE_INDEX_PATH: string;
export declare const MOBILE_TEMPLATE_PATH: string;
export declare const MOBILE_TEMPLATE_INDEX_PATH: string;
export declare const ADDONS_SRC_PATH: string;
export declare const ADDONS_BUILD_PATH: string;
export * from './mongo';
